#!/usr/bin/env bash
# action_transfer — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_action_transfer() {
    section "Models: action_transfer"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/FastWan/FastWan_T2V_14B_480p_lora_rank_128_bf16.safetensors" \
        "$MODELS/loras/FastWan_T2V_14B_480p_lora_rank_128_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/iossd-seselaoruyao/resolve/main/SESELAORUYAO.safetensors" \
        "$MODELS/loras/SESELAORUYAO.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/alibaba-pai-wan2-2-fun-reward-loras/resolve/main/Wan2.2-Fun-A14B-InP-low-noise-HPS2.1.safetensors" \
        "$MODELS/loras/Wan2.2-Fun-A14B-InP-low-noise-HPS2.1.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22-Lightning/old/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors" \
        "$MODELS/loras/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Pusa/Wan21_PusaV1_LoRA_14B_rank512_bf16.safetensors" \
        "$MODELS/loras/Wan21_PusaV1_LoRA_14B_rank512_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Wan21_Uni3C_controlnet_fp16.safetensors" \
        "$MODELS/controlnet/Wan21_Uni3C_controlnet_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/gerbyhorty76-videoloras/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors" \
        "$MODELS/diffusion_models/Wan22Animate/Wan2_2-Animate-14B_fp8_scaled_e4m3fn_KJ_v2.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Wan2_1_VAE_fp32.safetensors" \
        "$MODELS/vae/Wan2_1_VAE_fp32.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors" \
        "$MODELS/loras/WanAnimate_relight_lora_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-wan-2-1-comfyui-repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors" \
        "$MODELS/clip_vision/clip_vision_h.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-sdpose/resolve/main/checkpoints/sdpose_wholebody_fp16.safetensors" \
        "$MODELS/checkpoints/sdpose_wholebody_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/junkybyte-easy-vitpose/resolve/main/onnx/wholebody/vitpose-l-wholebody.onnx" \
        "$MODELS/detection/vitpose-l-wholebody.onnx"
    dl_pub "https://huggingface.co/fwwrsd/wan-ai-wan2-2-animate-14b/resolve/main/process_checkpoint/det/yolov10m.onnx" \
        "$MODELS/detection/yolov10m.onnx"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/umt5-xxl-enc-fp8_e4m3fn.safetensors" \
        "$MODELS/text_encoders/umt5-xxl-enc-fp8_e4m3fn.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ultralytics-yolo11/resolve/main/yolo11x-pose.pt" \
        "$MODELS/yolo/yolo11x-pose.pt"
    dl_pub "https://huggingface.co/fwwrsd/deepghs-real-person-detection/resolve/main/person_detect_v0_l_yv11.pt" \
        "$MODELS/yolo/real_person_detection_v0_l_yv11.pt"
}
