#!/usr/bin/env bash
# animator_v21 — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_animator_v21() {
    section "Models: animator_v21"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Wan21_Uni3C_controlnet_fp16.safetensors" \
        "$MODELS/controlnet/Wan21_Uni3C_controlnet_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/WanFun.reworked.safetensors" \
        "$MODELS/loras/WanFun.reworked.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/WanModel.safetensors" \
        "$MODELS/diffusion_models/WanModel.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/WanPusa.safetensors" \
        "$MODELS/loras/WanPusa.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/klip_vision.safetensors" \
        "$MODELS/clip_vision/klip_vision.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/light.safetensors" \
        "$MODELS/loras/light.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/text_enc.safetensors" \
        "$MODELS/text_encoders/text_enc.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/vae.safetensors" \
        "$MODELS/vae/vae.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-vitpose-comfy/resolve/main/onnx/vitpose_h_wholebody_model.onnx" \
        "$MODELS/detection/vitpose_h_wholebody_model.onnx"
    dl_pub "https://huggingface.co/fwwrsd/ofmhub/resolve/main/wan.reworked.safetensors" \
        "$MODELS/loras/wan.reworked.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/wan-ai-wan2-2-animate-14b/resolve/main/process_checkpoint/det/yolov10m.onnx" \
        "$MODELS/detection/yolov10m.onnx"
    dl_pub "https://huggingface.co/fwwrsd/kijai-vitpose-comfy/resolve/main/onnx/vitpose_h_wholebody_data.bin" \
        "$MODELS/detection/vitpose_h_wholebody_data.bin"
}
