#!/usr/bin/env bash
# ltx23_action_dual — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_ltx23_action_dual() {
    section "Models: ltx23_action_dual"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_audio_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_audio_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_video_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_video_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/jim507735-qwen-aio-remix/resolve/main/Qwen-Image-Edit-Remix-AIO.safetensors" \
        "$MODELS/checkpoints/Qwen-Image-Edit-Remix-AIO.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/gitmylo-ltx2-gemma-mirror/resolve/main/gemma_3_12B_it_fp8_e4m3fn.safetensors" \
        "$MODELS/text_encoders/gemma_3_12B_it_fp8_e4m3fn.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/diffusion_models/ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v3.safetensors" \
        "$MODELS/unet/ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v3.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3-22b-ic-lora-union-control/resolve/main/ltx-2.3-22b-ic-lora-union-control-ref0.5.safetensors" \
        "$MODELS/loras/ltx-2.3-22b-ic-lora-union-control-ref0.5.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/text_encoders/ltx-2.3_text_projection_bf16.safetensors" \
        "$MODELS/text_encoders/ltx-2.3_text_projection_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/assets/wholebody_anno.png" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/assets/wholebody_anno.png"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/decoder/decoder.safetensors" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/decoder/decoder.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/scheduler/scheduler_config.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/scheduler/scheduler_config.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/text_encoder/config.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/text_encoder/config.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/text_encoder/model.safetensors" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/text_encoder/model.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/tokenizer/merges.txt" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/tokenizer/merges.txt"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/tokenizer/special_tokens_map.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/tokenizer/special_tokens_map.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/tokenizer/tokenizer_config.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/tokenizer/tokenizer_config.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/tokenizer/vocab.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/tokenizer/vocab.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/unet/config.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/unet/config.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/unet/diffusion_pytorch_model.safetensors" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/unet/diffusion_pytorch_model.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/vae/config.json" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/vae/config.json"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/vae/diffusion_pytorch_model.safetensors" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/vae/diffusion_pytorch_model.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/teemosliang-sdpose-wholebody/resolve/main/yolo11x.pt" \
        "$MODELS/SDPose_OOD/SDPose-Wholebody/yolo11x.pt"
    dl_pub "https://huggingface.co/fwwrsd/yzd-v-dwpose/resolve/main/dw-ll_ucoco_384.onnx" \
        "/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v--DWPose/dw-ll_ucoco_384.onnx"
    dl_pub "https://huggingface.co/fwwrsd/yzd-v-dwpose/resolve/main/yolox_l.onnx" \
        "/workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v--DWPose/yolox_l.onnx"
}
