#!/usr/bin/env bash
# ltx_fishaudio — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_ltx_fishaudio() {
    section "Models: ltx_fishaudio"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3/resolve/main/ltx-2.3-22b-distilled-lora-384.safetensors" \
        "$MODELS/loras/LTX/LTX-2/ltx-2.3-22b-distilled-lora-384.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_audio_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_audio_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_video_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_video_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/quantstack-ltx-2-3-gguf/resolve/main/LTX-2.3-distilled-Q4_K_S.gguf" \
        "$MODELS/unet/LTXvideo/LTX-2/quantstack/LTX-2.3-distilled-Q4_K_S.gguf"
    dl_pub "https://huggingface.co/fwwrsd/kijai-melband-roformer-comfy/resolve/main/MelBandRoformer_fp16.safetensors" \
        "$MODELS/diffusion_models/MelBandRoFormer_comfy/MelBandRoformer_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/unsloth-gemma-3-12b-it-gguf/resolve/main/gemma-3-12b-it-Q2_K.gguf" \
        "$MODELS/text_encoders/gemma-3-12b-it-Q2_K.gguf"
    dl_pub "https://huggingface.co/fwwrsd/gitmylo-ltx2-gemma-mirror/resolve/main/gemma_3_12B_it_fp8_e4m3fn.safetensors" \
        "$MODELS/text_encoders/gemma_3_12B_it_fp8_e4m3fn.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/quantstack-ltx-2-3-gguf/resolve/main/ltx-2-3-22b-dev-Q4_K_S.gguf" \
        "$MODELS/unet/ltx-2-3-22b-dev-Q4_K_S.gguf"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/loras/ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors" \
        "$MODELS/loras/ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/diffusion_models/ltx-2.3-22b-distilled_transformer_only_fp8_scaled.safetensors" \
        "$MODELS/unet/ltx-2.3-22b-distilled_transformer_only_fp8_scaled.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3/resolve/main/ltx-2.3-spatial-upscaler-x2-1.1.safetensors" \
        "$MODELS/latent_upscale_models/ltx-2.3-spatial-upscaler-x2-1.1.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/text_encoders/ltx-2.3_text_projection_bf16.safetensors" \
        "$MODELS/text_encoders/ltx-2.3_text_projection_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/taeltx2_3.safetensors" \
        "$MODELS/vae/taeltx2_3.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/chat_template.jinja" \
        "$MODELS/fishaudioS2/s2-pro-fp8/chat_template.jinja"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/codec.pth" \
        "$MODELS/fishaudioS2/s2-pro-fp8/codec.pth"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/config.json" \
        "$MODELS/fishaudioS2/s2-pro-fp8/config.json"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/model.safetensors" \
        "$MODELS/fishaudioS2/s2-pro-fp8/model.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/quantization_info.json" \
        "$MODELS/fishaudioS2/s2-pro-fp8/quantization_info.json"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/special_tokens_map.json" \
        "$MODELS/fishaudioS2/s2-pro-fp8/special_tokens_map.json"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/tokenizer.json" \
        "$MODELS/fishaudioS2/s2-pro-fp8/tokenizer.json"
    dl_pub "https://huggingface.co/fwwrsd/drbaph-s2-pro-fp8/resolve/main/tokenizer_config.json" \
        "$MODELS/fishaudioS2/s2-pro-fp8/tokenizer_config.json"
    dl_wait_all
    make_link "$MODELS/diffusion_models/MelBandRoFormer_comfy/MelBandRoformer_fp16.safetensors" "$MODELS/diffusion_models/MelBandRoformer/MelBandRoformer_fp16.safetensors"
}
