#!/usr/bin/env bash
# t2i_zit_v7 — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_t2i_zit_v7() {
    section "Models: t2i_zit_v7"
    dl_pub "https://huggingface.co/fwwrsd/gemasai-4x-nmkd-siax-200k/resolve/main/4x_NMKD-Siax_200k.pth" \
        "$MODELS/upscale_models/4x_NMKD-Siax_200k.pth"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-lumina-image-2-0-repackaged/resolve/main/split_files/vae/ae.safetensors" \
        "$MODELS/vae/ae.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/bingsu-adetailer/resolve/main/face_yolov8m.pt" \
        "$MODELS/ultralytics/bbox/face_yolov8m.pt"
    dl_pub "https://huggingface.co/fwwrsd/brian334-female-breast-v4-7/resolve/main/female-breast-v4.7.pt" \
        "$MODELS/ultralytics/bbox/female-breast-v4.7.pt"
    dl_pub "https://huggingface.co/fwwrsd/civitai-misc-detectors/resolve/main/vagina-v4.2.pt" \
        "$MODELS/ultralytics/bbox/vagina-v4.2.pt"
    dl_pub "https://huggingface.co/fwwrsd/numz-seedvr2-comfyui/resolve/main/ema_vae_fp16.safetensors" \
        "$MODELS/seedvr2/ema_vae_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-flux2-klein-4b/resolve/main/split_files/text_encoders/qwen_3_4b.safetensors" \
        "$MODELS/text_encoders/qwen_3_4b.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfyuistudio-sam-vit-b-01ec64/resolve/main/sam_vit_b_01ec64.pth" \
        "$MODELS/sams/sam_vit_b_01ec64.pth"
    dl_pub "https://huggingface.co/fwwrsd/donuts-delivery-mix-v41/resolve/main/donutsdeliverymixV4_v41.safetensors" \
        "$MODELS/checkpoints/sdxl/donutsdeliverymixV4_v41.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/numz-seedvr2-comfyui/resolve/main/seedvr2_ema_7b_fp16.safetensors" \
        "$MODELS/seedvr2/seedvr2_ema_7b_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/alibaba-pai-z-image-turbo-fun-controlnet-union-2-1/resolve/main/Z-Image-Turbo-Fun-Controlnet-Union-2.1.safetensors" \
        "$MODELS/model_patches/z_image_CN/Z-Image-Turbo-Fun-Controlnet-Union-2.1.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-z-image-turbo/resolve/main/split_files/diffusion_models/z_image_turbo_bf16.safetensors" \
        "$MODELS/unet/z_image_turbo_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/ai-forever-real-esrgan/resolve/main/RealESRGAN_x2.pth" \
        "$MODELS/upscale_models/RealESRGAN_x2.pth"
}
