#!/usr/bin/env bash
# v2va_ltx23 — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_v2va_ltx23() {
    section "Models: v2va_ltx23"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/diffusion_models/ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v2.safetensors" \
        "$MODELS/diffusion_models/LTX2.3/ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v2.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_audio_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_audio_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/LTX23_video_vae_bf16.safetensors" \
        "$MODELS/vae/LTX23_video_vae_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/mlabonne-gemma-3-12b-abliterated-gguf/resolve/main/gemma-3-12b-it-abliterated.q6_k.gguf" \
        "$MODELS/text_encoders/gemma-3-12b-it-abliterated.q6_k.gguf"
    dl_pub "https://huggingface.co/fwwrsd/gitmylo-ltx2-gemma-mirror/resolve/main/gemma_3_12B_it_fp8_e4m3fn.safetensors" \
        "$MODELS/text_encoders/gemma_3_12B_it_fp8_e4m3fn.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3-fp8/resolve/main/ltx-2.3-22b-distilled-fp8.safetensors" \
        "$MODELS/text_encoders/ltx-2.3-22b-distilled-fp8.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3/resolve/main/ltx-2.3-spatial-upscaler-x2-1.0.safetensors" \
        "$MODELS/latent_upscale_models/ltx-2.3-spatial-upscaler-x2-1.0.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/text_encoders/ltx-2.3_text_projection_bf16.safetensors" \
        "$MODELS/text_encoders/ltx-2.3_text_projection_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-ltx2-3-comfy/resolve/main/vae/taeltx2_3.safetensors" \
        "$MODELS/vae/taeltx2_3.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/lightricks-ltx-2-3/resolve/main/ltx-2.3-22b-distilled-lora-384.safetensors" \
        "$MODELS/loras/LTX2.3/ltx-2.3-22b-distilled-lora-384.safetensors"
    dl_wait_all
    make_link "$MODELS/text_encoders/ltx-2.3-22b-distilled-fp8.safetensors" "$MODELS/checkpoints/ltx-2.3-22b-distilled-fp8.safetensors"
    make_link "$MODELS/text_encoders/ltx-2.3-22b-distilled-fp8.safetensors" "$MODELS/vae/ltx-2.3-22b-distilled-fp8.safetensors"
}
