#!/usr/bin/env bash
# wan22_gguf_longvideo — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_wan22_gguf_longvideo() {
    section "Models: wan22_gguf_longvideo"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Wan2_1_VAE_fp32.safetensors" \
        "$MODELS/vae/Wan2_1_VAE_fp32.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy-fp8-scaled/resolve/main/I2V/Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors" \
        "$MODELS/diffusion_models/Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy-fp8-scaled/resolve/main/I2V/Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors" \
        "$MODELS/diffusion_models/Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22_FunReward/Wan2.2-Fun-A14B-InP-HIGH-MPS_resized_dynamic_avg_rank_21_bf16.safetensors" \
        "$MODELS/loras/wan22/alibaba/Wan2.2-Fun-A14B-InP-HIGH-MPS_resized_dynamic_avg_rank_21_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22_FunReward/Wan2.2-Fun-A14B-InP-LOW-MPS_resized_dynamic_avg_rank_22_bf16.safetensors" \
        "$MODELS/loras/wan22/alibaba/Wan2.2-Fun-A14B-InP-LOW-MPS_resized_dynamic_avg_rank_22_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22-Lightning/old/Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors" \
        "$MODELS/loras/wan22/loras/Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/LoRAs/Wan22-Lightning/old/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors" \
        "$MODELS/loras/wan22/loras/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Pusa/Wan22_PusaV1_lora_HIGH_resized_dynamic_avg_rank_98_bf16.safetensors" \
        "$MODELS/loras/wan22/loras/Wan22_PusaV1_lora_HIGH_resized_dynamic_avg_rank_98_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/Pusa/Wan22_PusaV1_lora_LOW_resized_dynamic_avg_rank_98_bf16.safetensors" \
        "$MODELS/loras/wan22/loras/Wan22_PusaV1_lora_LOW_resized_dynamic_avg_rank_98_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/kijai-wanvideo-comfy/resolve/main/umt5-xxl-enc-bf16.safetensors" \
        "$MODELS/text_encoders/umt5-xxl-enc-bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/utnah-esrgan/resolve/main/2x_NMKD-UpgifLiteV2_210k.pth" \
        "$MODELS/upscale_models/2x_NMKD-UpgifLiteV2_210k.pth"
    dl_pub "https://huggingface.co/fwwrsd/dci05049-rife47/resolve/main/rife47.pth" \
        "$MODELS/rife/rife47.pth"
}
