#!/usr/bin/env bash
# x_mode — auto-generated by gen_deploy.py (DO NOT EDIT BY HAND)
models_x_mode() {
    section "Models: x_mode"
    dl_pub "https://huggingface.co/fwwrsd/xmode-loras-and-extras/resolve/main/loras/XXX.safetensors" \
        "$MODELS/loras/XXX.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/alibaba-pai-z-image-turbo-fun-controlnet-union/resolve/main/Z-Image-Turbo-Fun-Controlnet-Union.safetensors" \
        "$MODELS/model_patches/Z-Image-Turbo-Fun-Controlnet-Union.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-lumina-image-2-0-repackaged/resolve/main/split_files/vae/ae.safetensors" \
        "$MODELS/vae/ae.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/civitai-misc-detectors/resolve/main/Eyeful_v2-Paired.pt" \
        "$MODELS/ultralytics/bbox/Eyeful_v2-Paired.pt"
    dl_pub "https://huggingface.co/fwwrsd/civitai-misc-detectors/resolve/main/assdetailer.pt" \
        "$MODELS/ultralytics/bbox/assdetailer.pt"
    dl_pub "https://huggingface.co/fwwrsd/xmode-loras-and-extras/resolve/main/bbox/female_breast-v4.2.pt" \
        "$MODELS/ultralytics/bbox/female_breast-v4.2.pt"
    dl_pub "https://huggingface.co/fwwrsd/civitai-misc-detectors/resolve/main/vagina-v4.2.pt" \
        "$MODELS/ultralytics/bbox/vagina-v4.2.pt"
    dl_pub "https://huggingface.co/fwwrsd/x_mode_photos/resolve/main/models/ckpt/detect.safetensors" \
        "$MODELS/checkpoints/detect.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/numz-seedvr2-comfyui/resolve/main/ema_vae_fp16.safetensors" \
        "$MODELS/seedvr2/ema_vae_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/xmode-loras-and-extras/resolve/main/loras/gpu.safetensors" \
        "$MODELS/loras/gpu.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-flux2-klein-4b/resolve/main/split_files/text_encoders/qwen_3_4b.safetensors" \
        "$MODELS/text_encoders/qwen_3_4b.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/xmode-loras-and-extras/resolve/main/loras/real.safetensors" \
        "$MODELS/loras/real.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfyuistudio-sam-vit-b-01ec64/resolve/main/sam_vit_b_01ec64.pth" \
        "$MODELS/sams/sam_vit_b_01ec64.pth"
    dl_pub "https://huggingface.co/fwwrsd/numz-seedvr2-comfyui/resolve/main/seedvr2_ema_7b_sharp_fp16.safetensors" \
        "$MODELS/seedvr2/seedvr2_ema_7b_sharp_fp16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/comfy-org-z-image-turbo/resolve/main/split_files/diffusion_models/z_image_turbo_bf16.safetensors" \
        "$MODELS/unet/z_image_turbo_bf16.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/chat_template.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/chat_template.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/config.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/config.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/generation_config.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/generation_config.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/merges.txt" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/merges.txt"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/model-00001-of-00002.safetensors" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/model-00001-of-00002.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/model-00002-of-00002.safetensors" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/model-00002-of-00002.safetensors"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/model.safetensors.index.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/model.safetensors.index.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/preprocessor_config.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/preprocessor_config.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/tokenizer.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/tokenizer.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/tokenizer_config.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/tokenizer_config.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/video_preprocessor_config.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/video_preprocessor_config.json"
    dl_pub "https://huggingface.co/fwwrsd/qwen-qwen3-vl-4b-instruct/resolve/main/vocab.json" \
        "$MODELS/LLM/Qwen3-VL-4B-Instruct/vocab.json"
    dl_pub "https://huggingface.co/fwwrsd/utnah-esrgan/resolve/main/4x-UltraSharp.pth" \
        "$MODELS/upscale_models/4xUltrasharp_4xUltrasharpV10.pt"
}
